# Generated by Django 2.2.12 on 2020-04-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorrus', models.CharField(max_length=50)),
                ('majoreng', models.CharField(max_length=50)),
                ('majorkyr', models.CharField(max_length=50)),
                ('licence', models.CharField(blank=True, max_length=20)),
                ('year_of_educ', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGeneralInfo',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('sex', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('army_service', models.BooleanField(default=False)),
                ('rtoefl', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Academic leave', 'Academic leave'), ('Graduate', 'Graduate')], default='Active', max_length=10)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Major')),
            ],
        ),
    ]
