# Generated by Django 2.2.12 on 2020-04-14 10:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructorEducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_code', models.IntegerField()),
                ('major_kyr', models.CharField(max_length=100)),
                ('major_rus', models.CharField(max_length=100)),
                ('major_eng', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorGeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('sex', models.BooleanField(verbose_name=False)),
                ('dob', models.DateField(max_length=8)),
                ('family_status', models.CharField(choices=[('1', 'married'), ('2', 'single'), ('3', 'divorced')], max_length=50)),
                ('children', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('job_time', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time')], max_length=200)),
                ('where_are_from', models.CharField(choices=[('1', 'international'), ('2', 'local')], max_length=100)),
                ('degree', models.CharField(max_length=200)),
            ],
        ),
    ]
