# Generated by Django 2.2.12 on 2020-04-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcontactinfo',
            name='instructor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='instructors.InstructorGeneralInfo'),
        ),
        migrations.AddField(
            model_name='instructoreducationinfo',
            name='instructor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='instructors.InstructorGeneralInfo'),
        ),
    ]
